using ProjectEuler.Common;

namespace ProjectEuler.Problems
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem2
    {
        private int _UpperLimit;

        public int UpperLimit
        {
            get { return _UpperLimit; }
            set { _UpperLimit = value; }
        }

        public Problem2(int upperLimit)
        {
            UpperLimit = upperLimit;
        }        

        public int SumEvenValuedTerms()
        {
            int sum = 0;
            int fibonacciTerm;
            for (int i = 0; (fibonacciTerm = MathHelper.FibonacciMoivreBinet(i)) <= UpperLimit; i += 3)
                sum += fibonacciTerm;

            return sum;
        }
    }
}
